apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-cluster-tools
  namespace: argocd
spec:
  project: cluster-tools
  source:
    repoURL: https://github.com/Fro1m/clustertools.git
    targetRevision: main
    path: cluster-tools/argo-apps-manifests
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m