apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-stack-app
  namespace: argocd
spec:
  project: cluster-tools
  source:
    repoURL: https://github.com/Fro1m/clustertools.git
    targetRevision: main
    path: helm-charts/elastic-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
      - Prune=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m