apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-app
  namespace: argocd
spec:
  project: cluster-tools
  source:
    repoURL: https://github.com/Fro1m/clustertools.git
    targetRevision: main
    path: helm-charts/nginx-ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m